CREATE TABLE ZESTAWIENIA_SEANSOW_MIESIECZNE (
    ROK NUMBER,
    MIESIAC NUMBER,
    LICZBA_SEANSOW NUMBER,
    SREDNIA_CENA NUMBER(10,2),
    ESTYMOWANY_ZYSK NUMBER(12,2),
    FAKTYCZNY_ZYSK NUMBER(12,2)
);

CREATE OR REPLACE PROCEDURE Generuj_Zestawienie_Seansow_Miesiecze IS
BEGIN
    INSERT INTO ZESTAWIENIA_SEANSOW_MIESIECZNE
    SELECT
        EXTRACT(YEAR FROM s.DATA_GODZINA) AS ROK,
        EXTRACT(MONTH FROM s.DATA_GODZINA) AS MIESIAC,
        COUNT(DISTINCT s.ID_SEANS) AS LICZBA_SEANSOW,
        ROUND(AVG(s.CENA_BILETU), 2) AS SREDNIA_CENA,
        ROUND(SUM(NVL(r.LICZBA_MIEJSC, 0)) * ROUND(AVG(s.CENA_BILETU), 2), 2) AS ESTYMOWANY_ZYSK,
        ROUND(SUM(NVL(r.LICZBA_MIEJSC, 0) * s.CENA_BILETU), 2) AS FAKTYCZNY_ZYSK
    FROM SEANS s
    LEFT JOIN REZERWACJA r ON s.ID_SEANS = r.ID_SEANS
    GROUP BY EXTRACT(YEAR FROM s.DATA_GODZINA), EXTRACT(MONTH FROM s.DATA_GODZINA);
END;
