CREATE TABLE ZESTAWIENIA_MIESIECZNE (
    ROK NUMBER,
    MIESIAC NUMBER,
    LICZBA_BILETOW NUMBER
);

CREATE OR REPLACE PROCEDURE Generuj_Zestawienie_Miesieczne IS
BEGIN
    INSERT INTO ZESTAWIENIA_MIESIECZNE
    SELECT
        EXTRACT(YEAR FROM DATA_REZERWACJI),
        EXTRACT(MONTH FROM DATA_REZERWACJI),
        SUM(LICZBA_MIEJSC)
    FROM REZERWACJA
    GROUP BY EXTRACT(YEAR FROM DATA_REZERWACJI), EXTRACT(MONTH FROM DATA_REZERWACJI);
END;